<a href="https://colab.research.google.com/github/JBNUSFLEEHK/profile/blob/main/%EC%8A%A4%EA%B3%B5%EA%B8%B0_9%EC%A3%BC%EC%B0%A8_%EA%B0%95%EC%9D%98%EC%9E%90%EB%A3%8C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy를 활용한 행렬 계산


## numpy 모듈 불러오기

In [1]:
import numpy as np

## 행렬 생성 및 비교

In [2]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) # 1차원 행렬
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
c = np.array([[0, 1, 2], [3, 4, 5]])  # 2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
# 행렬의 크기
print(c.shape)


(2, 3)


In [5]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [ ]:
a

In [7]:
np.allclose(a, b)

False

## 행렬 (슬라이싱)

In [8]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [9]:
a[0, :]  # 첫번째 행 전체

array([0, 1, 2, 3])

In [10]:
a[:, 1]  # 두번째 열 전체

array([1, 5])

In [ ]:
a[1, 1:]  # 두번째 행의 두번째 열부터 끝열까지

In [12]:
a[:2, :2]

array([[0, 1],
       [4, 5]])

## 계산속도 비교하기 (벡터화)

In [13]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [14]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

CPU times: user 8.16 ms, sys: 0 ns, total: 8.16 ms
Wall time: 9.85 ms


In [15]:
%%time
z = x + y

CPU times: user 121 µs, sys: 0 ns, total: 121 µs
Wall time: 127 µs


## 중간고사 풀어보기

### 52. 고유값과 고유 벡터

$\begin{pmatrix}2&1\\1&2\\ \end{pmatrix}$


In [18]:
# 문제행렬 정의하기
mat_a = np.array([[2,1],[1,2]])

In [19]:
# 고유치 계산하기
np.linalg.eig(mat_a)

(array([3., 1.]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [22]:
#고유치
np.linalg.eig(mat_a)[0]

array([3., 1.])

In [24]:
#고유행렬
np.linalg.eig(mat_a)[1][:,0]

array([0.70710678, 0.70710678])

### 54. 행렬식
$\begin{vmatrix}1&4&0\\4&8&3\\ -1&0&2\end{vmatrix}$


In [25]:
# 행렬식 계산
mat_a = np.array([[1,4,0],[4,8,3],[-1,0,2]])
np.linalg.det(mat_a)

-27.999999999999996

### 55. 행렬식 구하시오.
$\begin{vmatrix}2&0&-4&6\\0&4&9.1&0\\ 0&0&5&5.8\\ 0&0&0&3\end{vmatrix}$


In [26]:
# 행렬식 계산
mat_a = np.array([[2, 0, -4, 6],[0,4,9.1,0],[0,0,5,5.8],[0,0,0,3]])
np.linalg.det(mat_a)

119.99999999999997

### 56. 역행렬
$\begin{bmatrix}4&1\\3&2\\ \end{bmatrix}$


In [27]:
mat_a = np.array([[4,1],[3,2]])
np.linalg.inv(mat_a)@mat_a

array([[ 1.00000000e+00,  0.00000000e+00],
       [-2.22044605e-16,  1.00000000e+00]])

### 57. 크래머 룰
$\begin{cases}
2x-4y &=&24\\
5x+2y &=&0
\end{cases}$

$x_1 = \frac{\begin{vmatrix}24 & -4 \\ 0 &2\end{vmatrix}}{\begin{vmatrix}2 & -4 \\ 5 &2\end{vmatrix}}$

In [28]:
mat_a = np.array([[2,-4],[5,2]])
vec_b = np.array([24,0])
mat_a

d = np.linalg.det(mat_a)
mat_x1 = mat_a.copy()
mat_x1[:,0] = vec_b
mat_x2 = mat_a.copy()
mat_x2[:,1] = vec_b

d1 = np.linalg.det(mat_a)
d2 = np.linalg.det(mat_a)

x1 = d1/d
x2 = d2/d
print(x1, x2)

1.0 1.0


In [31]:
# 행렬 풀이: np.linalg.solve(mat_a, vec_b)


### 58. 연립방정식 풀이
$\begin{cases}
x_1&-&x_2&+&x_3&=&0\\
-x_1 & +& x_2 & -& x_3 & = & 0\\
&&10x_2 & +& 25x_3 & = & 90\\
20x_1 & +& 10x_2 & & & = &80\\
\end{cases}$

In [32]:
mat_a = np.array([[1,-1,1],[0,10,25],[20,10,0]])
vec_b = np.array([0,90,80])

np.linalg.solve(mat_a, vec_b)

array([2., 4., 2.])

### 59. 역행렬 구하기
$\begin{bmatrix}2&-1&0\\1&0&-1\\1&0&1 \end{bmatrix}$


In [33]:
mat_a = np.array([[2,-1,0],[1,0,-1],[1,0,1]])
mat_a_inv = np.linalg.inv(mat_a)
mat_a_inv


array([[ 0. ,  0.5,  0.5],
       [-1. ,  1. ,  1. ],
       [ 0. , -0.5,  0.5]])

In [34]:
np.linalg.inv(mat_a) @ mat_a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])